CREATE FUNCTION loadjson(text)
RETURNS TEXT AS 'MODULE_PATHNAME','loadjson'
LANGUAGE C STRICT IMMUTABLE;

CREATE FUNCTION fs_size(text)
RETURNS bigint AS 'MODULE_PATHNAME','fs_size'
LANGUAGE C STRICT IMMUTABLE;

